#!/bin/bash

#execute with "sh bg_simulate_all &", then "disown";

sh create_ensemble.sh &> logfiles/log_create_ensemble
sh create_reference.sh &> logfiles/log_create_reference
python3.6 adjust_max.py &> logfiles/log_adjust_max

for i in {0..3}
do
python3.6 simulate.py <<EOF &> logfiles/log_simulate_$i 
$i
20
EOF
done

python3.6 plot_all.py &> logfiles/log_plot_all

